#!/bin/bash

# Make sure we are in the script directory
ScriptDIR=$(cd `dirname $0` && pwd)
if [ $ScriptDIR != $PWD ]; then
   echo "Ce script doit être executé depuis son dossier" 1>&2
   exit
fi

#On récupère le nombre de sessions actives de Yane
C=`sudo ./yane  -l | wc -l`

#On vérifie qu'aucune session n'est déjà lancée
if [ "$C" != "0" ] ; then
  echo "Une session est déjà lancée pour la fermer executez la commande:"
  echo "   STOP"
  exit

else
  #On copie les scripts dans le dossier partagé du Docker correspondant
  cp ./scripts/Serveur_DNS ./files/Serveur_DNS/etc/scripts/init
  cp ./scripts/Serveur_Web ./files/Serveur_Web/var/scripts/init
  cp ./scripts/FAI_Services ./files/FAI_Services/etc/scripts/init
  cp ./scripts/R1 ./files/R1/etc/scripts/init
  cp ./scripts/R2 ./files/R2/etc/scripts/init
  cp ./scripts/FAI_Acces ./files/FAI_Acces/etc/scripts/init
  cp ./scripts/BOX_1 ./files/BOX_1/etc/scripts/init
  cp ./scripts/BOX_2 ./files/BOX_2/etc/scripts/init
  cp ./scripts/Serveur_Web_Utilisateur ./files/Serveur_Web_Utilisateur/var/scripts/init
  echo 'Chargement des VM..'
  #On lance Yane
  sudo ./yane > /dev/null
  exit
fi
